### ISSUE TITLE
Doubly appending values from HTTP form and Query params

### ISSUE THREAD

**Issue by klische** [gomodule/oauth1#39]
The following line adds both form and query parameters from the URL
https://github.com/gomodule/oauth1/blob/9a59ed3b0a84f454c260f2f8f82918223fc5630f/oauth/oauth.go#L208

This results in duplicate encoded parameters. Only either/or should be appended. This would also make the method simpler by requiring only the *url.URL since that would contain the query parameters instead of requiring it and the url.Values.

**Comment by garyburd** [comment]
Post code showing the calls to this package that cause the problem.

**Comment by klische** [comment]
```go
package main

import (
		"github.com/gomodule/oauth1/oauth"
)

func main() {
	client := &http.Client{}
	req, reqErr := http.NewRequest("GET", "https://www.api.org", nil)
	q := req.URL.Query()
	q.Add("param1", "asdf")
	q.Add("param2", "zxcv")
	q.Add("param3", "foo")
	q.Add("param4", "bar")
	req.URL.RawQuery = q.Encode()

	oauthHeader := oauthClient.AuthorizationHeader(tokens, "GET", req.URL, q)
}```

**Comment by garyburd** [comment]
Adding query and form parameters to the base string is correct. Modify the application to specify the parameters using either the query or the form, not both.  For example:

	oauthHeader := oauthClient.AuthorizationHeader(tokens, "GET", req.URL, nil)
