### ISSUE TITLE
oauth_consumer_key and oauth_token set to same value

### ISSUE THREAD

**Issue by nuliknol** [gomodule/oauth1#45]
When you create the `Authorization` header , you set the `oauth_consumer_key` and `oauth_token` to the same value. Are you sure this is correct? For Twitter it expects the App key in `oauth_consumer_key` and the token in `oauth_token`, so the values should be different.  Or maybe I am missing something?

**Comment by garyburd** [comment]
The package does not mix up the values.  Check the use of those values in your application.

See https://play.golang.org/p/FEVurdK3i7T

**Comment by nuliknol** [comment]
@garyburd 

no, I am talking about this code:

```
func (c *Client) oauthParams(r *request) (map[string]string, error) {
	oauthParams := map[string]string{
		"oauth_consumer_key":     c.Credentials.Token,
		"oauth_signature_method": c.SignatureMethod.String(),
		"oauth_version":          "1.0",
	}
```

this instruction:

     "oauth_consumer_key":     c.Credentials.Token,

is setting consumer key to the value of the token, but it should be the set to the API Key Twitter assigns to you

I actually had to fix it for Twitter to work.

**Comment by garyburd** [comment]
The application specifies the consumer key and secret with [Client.Credentials](https://pkg.go.dev/github.com/gomodule/oauth1/oauth#Client.Credentials).  

The initialization `"oauth_consumer_key": c.Credentials.Token` sets the consumer key parameter to the consumer key specified by the application.
