### ISSUE TITLE
No forward slash between host and path

### ISSUE THREAD

**Issue by adam-hanna** [gomodule/oauth1#46]
https://github.com/gomodule/oauth1/blob/4e4c69ae721f048e9f4c618e7131e6178c2a9efb/oauth/oauth.go#L201

Should this read:

```golang
w.Write(encode(host, false))
w.Write(encode("/", false))
w.Write(encode(path, false))
```

**Comment by garyburd** [comment]
There's no need to add a slash because `path` has a leading slash.  See [the tests](https://github.com/gomodule/oauth1/blob/4e4c69ae721f048e9f4c618e7131e6178c2a9efb/oauth/oauth_test.go#L56-L224).  The base strings have a `/` (encoded as %2f) following the host.

**Comment by adam-hanna** [comment]
#47 47

**Comment by garyburd** [comment]
An application can pass an invalid HTTP [request URI](https://pkg.go.dev/net/url#URL.RequestURI) through to writeBaseString by calling [SetAuthorizationHeader](https://pkg.go.dev/github.com/gomodule/oauth1/oauth#Client.SetAuthorizationHeader) or [AuthorizationHeader](https://pkg.go.dev/github.com/gomodule/oauth1/oauth#Client.AuthorizationHeader) with an invalid [URL.Path](https://pkg.go.dev/net/url#URL.Path) or [URL.Opaque](https://pkg.go.dev/net/url#URL.Opaque) field.  For consistency [with the net/http package](https://github.com/golang/go/blob/65535bfe6dad2cb7535f6a5647b288e4489608f9/src/net/http/request.go#L584),  this package [should use the request URI as-is](https://github.com/gomodule/oauth1/blob/273b3bd3876e055d4d36d859fdc3c52a49bee052/oauth/oauth.go#L189) (except for stripping the query). 

Is there another scenario where the slash goes missing?
